### ISSUE TITLE
Application validation did not succeed. Version 1.4.2 

### ISSUE THREAD

**Issue by tripiti** [coldphysics/experiment-control#32]
**Describe the bug**
New Version 1.4.2 fails during install with Application validation did not succeed. Unable to continue

**To Reproduce**
Download new 1.4.2 version an execute setup.exe
Error message appears and stops the installation process

**Expected behavior**
Application should install without any error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Control Version 1.4.2
 - Hardware Type AdWin

**Additional context**
PLATFORM VERSION INFO
	Windows 			: 10.0.19041.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4240.0 built by: NET48REL1LAST_B
	clr.dll 			: 4.8.4220.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4240.0 built by: NET48REL1LAST_B
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Rubidium/Downloads/releases-master/releases-master/v1.4.2/MainProject.application
	Application url			: file:///C:/Users/Rubidium/Downloads/releases-master/releases-master/v1.4.2/Application%20Files/MainProject_1_4_2_0/MainProject.exe.manifest

IDENTITIES
	Deployment Identity		: MainProject.application, Version=1.4.2.0, Culture=en-US, PublicKeyToken=0000000000000000, processorArchitecture=amd64

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Rubidium\Downloads\releases-master\releases-master\v1.4.2\MainProject.application resulted in exception. Following failure messages were detected:
		+ Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		+ File, MainProject.exe.manifest, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [29.09.2020 08:01:41] : Activation of C:\Users\Rubidium\Downloads\releases-master\releases-master\v1.4.2\MainProject.application has started.
	* [29.09.2020 08:01:41] : Processing of deployment manifest has successfully completed.
	* [29.09.2020 08:01:41] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [29.09.2020 08:01:41] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, MainProject.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by ghareeb-falazi** [comment]
For some reason, Github is messing with the file contents so that their hash (digest) is not what is expected. I zipped the release  before uploading it to Github. Not very convenient but seems to work. Please try downloading the release again, unzip it and install it. If something goes wrong please reopen this issue.
